### ISSUE TITLE
undefined local variable or method `options' for #<Gruf::Sentry::ClientInterceptor:0x00007f9789a57260 @options={}>

### ISSUE THREAD

**Issue by semirart** [bigcommerce/gruf-sentry#1]
Hi!

There is an error when gruf-sentry tries to send the exception to sentry:

> #<NameError: undefined local variable or method `options' for #<Gruf::Sentry::ClientInterceptor:0x00007f9789a57260 @options={}>

```
gruf-sentry-0.0.1/lib/gruf/sentry/error_parser.rb:44:in `error_classes'
gruf-sentry-0.0.1/lib/gruf/sentry/error_parser.rb:36:in `error?'
gruf-sentry-0.0.1/lib/gruf/sentry/client_interceptor.rb:35:in `rescue in call'
gruf-sentry-0.0.1/lib/gruf/sentry/client_interceptor.rb:32:in `call'
gruf-2.8.1/lib/gruf/interceptors/client_interceptor.rb:54:in `request_response'
```

For now I monkeypatch the gem to make it work:
```
# monkeypatch to fix error
module Gruf::Sentry::ErrorParser
  attr :options
end
```

**Comment by splittingred** [comment]
Thanks for this! It's been fixed and released in https://rubygems.org/gems/gruf-sentry/versions/0.1.1
